version: 0.0
os: linux
files:
  - source: /
    destination: /app
    overwrite: true
hooks:
  BeforeInstall:
    - location: aws/scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/build_app
      timout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/start_server
      timeout: 300
      runas: root