#!/bin/bash

cd /app

curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
yum install nodejs -y

if [ -d "../node_modules" ] 
then
  rm -rf "../node_modules"
fi

npm install
npm install react react-dom react-scripts
npm install pm2 -g